### ISSUE TITLE
Not a issue. Just make a README.md

### ISSUE THREAD

**Issue by ajinzrathod** [vandan103/ecommerce#8]
Please make a README.md file, so that the user can know which java version and dependencies needs to be installed. And provide all such necessary details, please.

**Comment by vandan103** [comment]
ok ajinzrathod  
java version: java 17
dependencies :  JDBC- mysql connector
tools: web server,eclipse,xampp

guide:
please import mysql database with name: **ecommerce** as i have added this sql file in projects.
